/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'siti-archeologici': SitiArcheologici;
    chiese: Chiese;
    edifici: Edifici;
    collezioni: Collezioni;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'siti-archeologici': SitiArcheologiciSelect<false> | SitiArcheologiciSelect<true>;
    chiese: ChieseSelect<false> | ChieseSelect<true>;
    edifici: EdificiSelect<false> | EdificiSelect<true>;
    collezioni: CollezioniSelect<false> | CollezioniSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('it' | 'en') | ('it' | 'en')[];
  globals: {
    home: Home;
    museo: Museo;
    'museo-storia': MuseoStoria;
    'museo-sede': MuseoSede;
    'museo-servizi': MuseoServizi;
    'museo-libreria': MuseoLibreria;
    'museo-contatti': MuseoContatti;
    pau: Pau;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    museo: MuseoSelect<false> | MuseoSelect<true>;
    'museo-storia': MuseoStoriaSelect<false> | MuseoStoriaSelect<true>;
    'museo-sede': MuseoSedeSelect<false> | MuseoSedeSelect<true>;
    'museo-servizi': MuseoServiziSelect<false> | MuseoServiziSelect<true>;
    'museo-libreria': MuseoLibreriaSelect<false> | MuseoLibreriaSelect<true>;
    'museo-contatti': MuseoContattiSelect<false> | MuseoContattiSelect<true>;
    pau: PauSelect<false> | PauSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'it' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    'hero-16-9-avif'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'hero-16-9-webp'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'card-4-3-avif'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'card-4-3-webp'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'square-1-1-avif'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'square-1-1-webp'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'banner-21-9-avif'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'banner-21-9-webp'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Itinerari/siti archeologici della città (mura, ninfeo, acropoli, ecc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siti-archeologici".
 */
export interface SitiArcheologici {
  id: number;
  slug: string;
  title: string;
  subtitle?: string | null;
  /**
   * Testo del sito. Può contenere tag HTML inline (es. <em>...</em>) già presenti nel testo originale.
   */
  description?: string | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  ordine?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chiese".
 */
export interface Chiese {
  id: number;
  slug: string;
  title: string;
  subtitle?: string | null;
  /**
   * Può contenere tag HTML inline (es. <em>...</em>).
   */
  description?: string | null;
  history?: string | null;
  features?: string | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  ordine?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edifici".
 */
export interface Edifici {
  id: number;
  slug: string;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  history?: string | null;
  architecture?: string | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  ordine?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collezioni".
 */
export interface Collezioni {
  id: number;
  slug: string;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  heroImage?: (number | null) | Media;
  items?:
    | {
        name: string;
        description?: string | null;
        image?: (number | null) | Media;
        object?: string | null;
        provenance?: string | null;
        dating?: string | null;
        room?: string | null;
        bibliography?: string | null;
        id?: string | null;
      }[]
    | null;
  ordine?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'siti-archeologici';
        value: number | SitiArcheologici;
      } | null)
    | ({
        relationTo: 'chiese';
        value: number | Chiese;
      } | null)
    | ({
        relationTo: 'edifici';
        value: number | Edifici;
      } | null)
    | ({
        relationTo: 'collezioni';
        value: number | Collezioni;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        'hero-16-9-avif'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'hero-16-9-webp'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'card-4-3-avif'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'card-4-3-webp'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'square-1-1-avif'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'square-1-1-webp'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'banner-21-9-avif'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'banner-21-9-webp'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siti-archeologici_select".
 */
export interface SitiArcheologiciSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  ordine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chiese_select".
 */
export interface ChieseSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  history?: T;
  features?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  ordine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edifici_select".
 */
export interface EdificiSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  history?: T;
  architecture?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  ordine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collezioni_select".
 */
export interface CollezioniSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  heroImage?: T;
  items?:
    | T
    | {
        name?: T;
        description?: T;
        image?: T;
        object?: T;
        provenance?: T;
        dating?: T;
        room?: T;
        bibliography?: T;
        id?: T;
      };
  ordine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroTitle?: string | null;
  heroTitleAccent?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  heroCtaLabel?: string | null;
  introTitle?: string | null;
  introText?: string | null;
  /**
   * Le 3 card della home (link verso itinerario/collezione/museo). Il collegamento resta fisso nel template, qui si edita solo testo e immagine.
   */
  featuredCards?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  newsSectionTitle?: string | null;
  newsItems?:
    | {
        title: string;
        date?: string | null;
        excerpt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo".
 */
export interface Museo {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Paragrafi separati da riga vuota, come nel sito attuale.
   */
  intro?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-storia".
 */
export interface MuseoStoria {
  id: number;
  heroImage?: (number | null) | Media;
  /**
   * Es. "La Ricerca e la Nascita", "Divulgazione e Futuro".
   */
  sections?:
    | {
        heading: string;
        /**
         * Paragrafi separati da riga vuota.
         */
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  sideImages?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  sale?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-sede".
 */
export interface MuseoSede {
  id: number;
  subtitle?: string | null;
  heading?: string | null;
  /**
   * Paragrafi separati da riga vuota.
   */
  body?: string | null;
  exteriorImage?: (number | null) | Media;
  /**
   * Es. "XIII Secolo", "Centro Storico", "Architettura".
   */
  factCards?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  interiorImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-servizi".
 */
export interface MuseoServizi {
  id: number;
  heroImage?: (number | null) | Media;
  services?:
    | {
        /**
         * Nome icona lucide-react usata dal frontend.
         */
        icon: 'BookOpen' | 'Archive' | 'GraduationCap' | 'Camera' | 'Wifi' | 'Accessibility';
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  researchSectionTitle?: string | null;
  researchText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-libreria".
 */
export interface MuseoLibreria {
  id: number;
  heroImage?: (number | null) | Media;
  books?:
    | {
        title: string;
        author?: string | null;
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  merchandise?:
    | {
        title: string;
        description?: string | null;
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-contatti".
 */
export interface MuseoContatti {
  id: number;
  subtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pau".
 */
export interface Pau {
  id: number;
  heroTitle?: string | null;
  heroTitleAccent?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  introHeading?: string | null;
  /**
   * Paragrafi separati da riga vuota.
   */
  introText?: string | null;
  objectives?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  sideImages?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  openingHours?:
    | {
        days?: string | null;
        hours?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  holidayNote?: string | null;
  ticketPrice?: string | null;
  howToArrive?:
    | {
        mode: 'car' | 'train';
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  regolamentoPdf?: (number | null) | Media;
  cartaServiziPdf?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroTitle?: T;
  heroTitleAccent?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroCtaLabel?: T;
  introTitle?: T;
  introText?: T;
  featuredCards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  newsSectionTitle?: T;
  newsItems?:
    | T
    | {
        title?: T;
        date?: T;
        excerpt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo_select".
 */
export interface MuseoSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-storia_select".
 */
export interface MuseoStoriaSelect<T extends boolean = true> {
  heroImage?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  sideImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  sale?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-sede_select".
 */
export interface MuseoSedeSelect<T extends boolean = true> {
  subtitle?: T;
  heading?: T;
  body?: T;
  exteriorImage?: T;
  factCards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  interiorImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-servizi_select".
 */
export interface MuseoServiziSelect<T extends boolean = true> {
  heroImage?: T;
  services?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  researchSectionTitle?: T;
  researchText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-libreria_select".
 */
export interface MuseoLibreriaSelect<T extends boolean = true> {
  heroImage?: T;
  books?:
    | T
    | {
        title?: T;
        author?: T;
        price?: T;
        id?: T;
      };
  merchandise?:
    | T
    | {
        title?: T;
        description?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "museo-contatti_select".
 */
export interface MuseoContattiSelect<T extends boolean = true> {
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pau_select".
 */
export interface PauSelect<T extends boolean = true> {
  heroTitle?: T;
  heroTitleAccent?: T;
  heroSubtitle?: T;
  heroImage?: T;
  introHeading?: T;
  introText?: T;
  objectives?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  sideImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  address?: T;
  phone?: T;
  email?: T;
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        closed?: T;
        id?: T;
      };
  holidayNote?: T;
  ticketPrice?: T;
  howToArrive?:
    | T
    | {
        mode?: T;
        description?: T;
        id?: T;
      };
  regolamentoPdf?: T;
  cartaServiziPdf?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}