version: '3'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: museosegni
      POSTGRES_PASSWORD: password
      POSTGRES_DB: museosegni_cms
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
